### PR TITLE
Arkibud's new input

### PR DESCRIPTION
**Pull request by arkibud**

### CODE REVIEW

**Comment by Pranav108** [comment]
Try to minimize the irrelevant changes.
you have to add your info below the last line only(also mind the extra spaces).
Try to improve your change.
let me know if you got any doubt

**Comment by arkibud** [comment]
Ok thank you

**Comment by arkibud** [comment]
Pranav Si, i see the mistakes with the extra spaces but can you shed light
on what irrelevant changes i have made, also what you meant by adding the
info in the last like because in my system i wrote the info in the next
line just after the last input. Do check the file for reference thank you
again.

**Comment by Pranav108** [comment]
@arkibud  This is the change that you have done 
Screenshot (578)

And this is how it should be done
image

This is not a big issue, if you don't get it leave it for now.
Anyway I'll merge it now, no need to worry about it.

**Pull request merged**
